pipeline {
    
    agent any
    
    environment {
        registryName = "petclinic"
        registryUrl = "docker.io/"
        registryCredentials = "DOCKER_HUB_CREDS"
        registry = "mklimas/petclinic"
        dockerImage = ""
        IMAGE_NUMBER = ""
        WEB_IMAGE_NAME="${registry}:${BUILD_NUMBER}"
    }
    
    stages {
        stage ('Checkout') {
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Withel/master-thesis-spring-petclinic']]])
            }
        }
        stage ('Build JAR file') {
            steps {
                sh './gradlew build'
            }

            post {
                success {
                    junit 'build/test-results/test/TEST-*.xml'    
                }
            }
        }
        
        stage ('Build Docker image') {
            steps {                
                script {
                    dockerImage = docker.build("mklimas/petclinic")
                    dockerimage = docker.build("$registry")
                }
            }
        }
        
        stage('Push Image') {
            steps{   
                script {
                    docker.withRegistry( '', registryCredentials ) {
                        // IMAGE_NUMBER = "${env.BUILD_NUMBER}"
                        // sh 'echo TEST DUPA'
                        // sh 'echo "$IMAGE_NUMBER"'
                        dockerImage.push("${env.BUILD_NUMBER}")
                        dockerImage.push("latest")
                    }
                }
            }
        }

        stage ('Deploy') {
            steps {
                    sh 'kubectl set image deployment/petclinic petclinic=$WEB_IMAGE_NAME'
            }
        }
    }
}